server:
  port: 8081

spring:
  application:
    name: walletApp

  data:
    mongodb:
      host: localhost
      port: 27017
      database: MyDB

      logging:
        level:
          com:
            example:
              filterPoc:DEBUG